name: Unittest

on:
  pull_request:
  push:
    branches:
      - master
      - stable*


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        shell: bash
        run: |
          echo "This is a testrun"